// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mmcmimmzgvovmvnbsznv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1tY21pbW16Z3Zvdm12bmJzem52Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxOTE2ODIsImV4cCI6MjA2MTc2NzY4Mn0.Uz2UXr9llQCxDJNY-OJaspAmie1v9gfVCYmyEm3SdiU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);